server:
  port: 8083

spring:
  application:
    name: order-service
  cloud:
    nacos:
      username: nacos
      password: 123456
      config:
        enabled: false
      discovery:
        server-addr: 127.0.0.1:8848

springdoc:
  api-docs:
    group: order-service
  swagger-ui:
    path: /swagger-ui.html

feign:
  client:
    config:
        default:
            connectTimeout: 5000
            readTimeout: 5000
